### ISSUE TITLE
HSL text input in 'enter a color'

### ISSUE THREAD

**Issue by obscuredetour** [obscuredetour/color-deck#1]
This breaks the app and it must be reloaded.

This is due to a bug in [iro.js](https://iro.js.org/) where setting the color by an HSL string breaks the color picker.

This bug can be recreated in the [iro.js codepen demo](https://codepen.io/rakujira/pen/WZOeNq?editors=0011).
In the console type `colorPicker.color.hslString = 'hsl(182, 35%, 65%)'`
Hex and RGB string values are capable of setting the color with their respective methods. Attempting to parse an HSL string using **_iro.js_** also results in an error.

**Solutions and/or Workarounds**
- Parse the HSL string (using alternative methods [not iro.js]) and set the color using a hex or rgb value.
- Set a pattern on the HTML input element to restrict HSL input 😬

**Comment by jaames** [comment]
Hey @obscuredetour,

I just found this while looking for projects that are using iro.js in the wild. I'm sorry to see that you have encountered a bug with the library though. It would be great if you could open up an [issue thread](https://github.com/jaames/iro.js/issues) so we could work towards a fix. :) 

This is a neat app by the way -- nice job!

**Comment by obscuredetour** [comment]
Fixed at f199065f2262544c9c8ab9e58869cd9c95acd201 - iro.js updated to v3.5.5 hotfix for HSL strings.
